default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marketplace_api_development
  host: localhost
  port: 5432
  username: Wander
  password: google123

test:
  <<: *default
  database: marketplace_api_test
  host: localhost
  port: 5432
  username: Wander
  password: google123
  
production:
  <<: *default
  database: marketplace_api_production
  username: marketplace_api
  password: <%= ENV["MARKETPLACE_API_DATABASE_PASSWORD"] %>
